-- MySQL Script generated by MySQL Workbench
-- Wed Jun 14 17:55:13 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema friend
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema friend
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `friend` DEFAULT CHARACTER SET utf8 ;
USE `friend` ;

-- -----------------------------------------------------
-- Table `friend`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `friend`.`friends` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  `created_at` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
